name: Deploy Shadowsocks

on:
  workflow_dispatch:
    inputs:
      action:
        description: "选择执行的操作"
        required: true
        default: "plan"
        type: choice
        options: [ plan, apply ]

env:
  TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_cloudflare_account_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_email_address: ${{ vars.EMAIL_ADDRESS }}
  TF_VAR_domain: ${{ vars.DOMAIN }}
  TF_VAR_subdomain: ${{ vars.SUBDOMAIN }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        if: ${{ inputs.action == 'plan' }}
        run: terraform plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}